name: Pipeline with Build and Jest Test in 2 Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

  tests:
    runs-on: ubuntu-22.04
    needs: build # Test-Job wartet, bis der Build-Job erfolgreich ist
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and run Test
        run: |
          npm install
          npm test
